version: "3"
services:

  db:
    image: postgres:14
    ports:
      - "5433"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=app

  web:
    build:
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3G
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "python etl/main.py && uvicorn app.main:app --host  0.0.0.0 --port 8000"
    volumes:
      - .:/api
    environment:
      - LOCAL_RUN=1
      - DATASET_URL=https://s3.eu-west-3.amazonaws.com/datateam.matrixiangroup/data-engineer-assignment/es-addresses.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4VO55AJ2MGKSCBVQ%2F20230801%2Feu-west-3%2Fs3%2Faws4_request&X-Amz-Date=20230801T061647Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d4b7d7d6f822b67c83a01edf62ca4e30ebe85ec4fc3b0e9745008aaa3646aacd
      - POSTGRES_HOST=db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=postgres
      - OUTPUT_FOLDER=data
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
volumes:
  app-db-data: